"""
Slack transport — the ONLY outbound notification surface.

Two hard-separated routes (ron_clanker-y5f5 redesign):

  RON   the main league channel. Carries Ron's VOICE only — team
        announcements and post-GW reviews, generated exclusively by
        ron_clanker/llm_banter.py. No status spam, no stack traces.

  OPS   a private channel (#ron-ops) for the human: pipeline errors,
        scout reports, price predictions, dry/technical output. If
        SLACK_OPS_WEBHOOK_URL is not configured these messages go to
        the LOG, never to the main channel — API errors in the league
        chat looked terrible and that must not recur.

This module is transport only. It does not format, template, or
characterise anything: personality lives in one place (llm_banter) and
plumbing lives here. (The old block-builder helpers for reviews and
transfer cards had zero callers and duplicated persona-adjacent
formatting; removed.)
"""

import logging
import os
from typing import Optional

import requests

logger = logging.getLogger('ron_clanker.slack')


class SlackNotifier:
    """Webhook-based Slack sender with separated ron/ops routes."""

    def __init__(self, webhook_url: Optional[str] = None,
                 ops_webhook_url: Optional[str] = None):
        self.webhook_url = webhook_url or os.getenv('SLACK_WEBHOOK_URL')
        self.ops_webhook_url = (ops_webhook_url
                                or os.getenv('SLACK_OPS_WEBHOOK_URL'))
        self.enabled = bool(self.webhook_url)
        if not self.webhook_url:
            logger.warning("No SLACK_WEBHOOK_URL configured — main-channel "
                           "notifications disabled")
        if not self.ops_webhook_url:
            logger.info("No SLACK_OPS_WEBHOOK_URL configured — ops messages "
                        "will be logged only")

    # ------------------------------------------------------------------

    def _post(self, url: str, text: str) -> bool:
        try:
            response = requests.post(url, json={'text': text}, timeout=15)
            if response.status_code == 200:
                return True
            logger.error("Slack post failed: HTTP %s %s",
                         response.status_code, response.text[:200])
            return False
        except Exception as e:
            logger.error("Slack post failed: %s", e)
            return False

    # ------------------------------------------------------------------

    def send_ron(self, text: str) -> bool:
        """Ron's voice -> the main league channel. Callers must pass
        text already generated by ron_clanker/llm_banter.py (or its
        deterministic fallback)."""
        if not self.webhook_url:
            logger.info("[ron-channel suppressed] %s", text[:120])
            return False
        return self._post(self.webhook_url, text)

    def send_ops(self, text: str, context: Optional[str] = None) -> bool:
        """Technical/ops message -> private #ron-ops. NEVER the main
        channel: without an ops webhook this logs and returns False."""
        body = f"[{context}] {text}" if context else text
        if not self.ops_webhook_url:
            logger.warning("[ops] %s", body)
            return False
        return self._post(self.ops_webhook_url, f":wrench: {body}")

    # ------------------------------------------------------------------
    # Back-compat names used by the pipeline scripts

    def send_team_announcement(self, announcement_text: str,
                               gameweek: int) -> bool:
        del gameweek  # the announcement text already carries the GW
        return self.send_ron(announcement_text)


def send_team_announcement_to_slack(announcement: str, gameweek: int) -> bool:
    return SlackNotifier().send_team_announcement(announcement, gameweek)


def send_ops_alert(text: str, context: Optional[str] = None) -> bool:
    """Module-level convenience for cron scripts reporting failures."""
    return SlackNotifier().send_ops(text, context=context)
